### ISSUE TITLE
starting errors

### ISSUE THREAD

**Issue by DjangoFR** [mitmproxy/docker-releases#18]
Tried to start mitmproxy from docker-compose.yml:

```
  mitmproxy:
    image: mitmproxy/mitmproxy
    ports:
      - "8080:8080"
    volumes:
       - ./storage/mitmproxy/.mitmproxy:/home/mitmproxy/.mitmproxy
```

the result was:
```
$ docker-compose up mitmproxy
Pulling mitmproxy (mitmproxy/mitmproxy:latest)...
latest: Pulling from mitmproxy/mitmproxy
019300c8a437: Pull complete
b6f2ab2e0e43: Pull complete
a62f1b73f579: Pull complete
d24c6724c3ed: Pull complete
Digest: sha256:6a38773c1dc2d0751e6ac0a73148e59030ebc143a47a20904966ecf3de3b2860
Status: Downloaded newer image for mitmproxy/mitmproxy:latest
Creating rxsymfonydev_mitmproxy_1
Attaching to rxsymfonydev_mitmproxy_1
mitmproxy_1  | Traceback (most recent call last):
mitmproxy_1  |   File "/usr/lib/python3.5/site-packages/mitmproxy/tools/console/master.py", line 281, in run
mitmproxy_1  |     self.loop.run()
mitmproxy_1  |   File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
mitmproxy_1  |     self._run()
mitmproxy_1  |   File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
mitmproxy_1  |     self.event_loop.run()
mitmproxy_1  |   File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
mitmproxy_1  |     self._loop()
mitmproxy_1  |   File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
mitmproxy_1  |     self._watch_files[fd]()
mitmproxy_1  |   File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
mitmproxy_1  |     event_loop, callback, self.get_available_raw_input())
mitmproxy_1  |   File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 427, in get_available_raw_input
mitmproxy_1  |     codes = self._get_gpm_codes() + self._get_keyboard_codes()
mitmproxy_1  |   File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 501, in _get_keyboard_codes
mitmproxy_1  |     code = self._getch_nodelay()
mitmproxy_1  |   File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 635, in _getch_nodelay
mitmproxy_1  |     return self._getch(0)
mitmproxy_1  |   File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 545, in _getch
mitmproxy_1  |     return ord(os.read(self._term_input_file.fileno(), 1))
mitmproxy_1  | TypeError: ord() expected a character, but string of length 0 found
mitmproxy_1  | 
mitmproxy_1  | mitmproxy has crashed!
mitmproxy_1  | Please lodge a bug report at:
mitmproxy_1  |  https://github.com/mitmproxy/mitmproxy
mitmproxy_1  | Shutting down...
rxsymfonydev_mitmproxy_1 exited with code 0
```
... any suggestions?

**Comment by gkumarpatel** [comment]
You may want to use `tty:true` if you want to use mitmproxy or you may use use `mitmdump` by providing `command: mitmdump` in your docker-compose file.
